# 分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

# qq邮箱配置
spring:
  mail:
    host: smtp.qq.com
    port: 587
    protocol: smtp
    username: 1106126069@qq.com
    password: jtjqpowyzqnrbaaa
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: 121.196.154.123
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    timeout: 30000


